name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t dind-awscli-python .

      - name: Run test
        run: |
          docker run --rm dind-awscli-python docker --version
          docker run --rm dind-awscli-python docker-compose --version
